
[deployment]
deploymentTarget = "cloudrun"
ignorePorts = false

[deployment.build]
run = ["sh", "-c", "pip install --upgrade pip setuptools wheel && pip install -e . && pip install gunicorn>=23.0.0"]

[deployment.run]
run = ["python", "deployment_start.py"]

[[deployment.env]]
key = "FLASK_ENV"
value = "production"

[[deployment.env]]
key = "PYTHONUNBUFFERED"
value = "1"

[[deployment.env]]
key = "PORT"
value = "8080"

# Database configuration - using the same DATABASE_URL as dev
[[deployment.env]]
key = "DATABASE_URL"
value = "${DATABASE_URL}"

[[deployment.env]]
key = "SESSION_SECRET"
value = "${SESSION_SECRET}"
