# Configuration file for Replit Deployments
run = "python production_server.py"
deploymentTarget = "cloudrun"

# Health check endpoint
healthCheckPath = "/health_check"

# Environment configuration
[env]
# These values are used during deployment
ENVIRONMENT = "production"
DEBUG = "false"

# Specify the port mapping for Replit
[[ports]]
localPort = 8080
externalPort = 80