
[deployment]
deploymentTarget = "cloudrun"
ignorePorts = false

[deployment.build]
run = ["pip", "install", "-r", "requirements.txt"]

[deployment.run]
run = ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "1", "--timeout", "300", "--keep-alive", "2", "--max-requests", "1000", "main:app"]

[[deployment.env]]
key = "FLASK_ENV"
value = "production"

[[deployment.env]]
key = "PYTHONUNBUFFERED"
value = "1"


