
[deployment]
deploymentTarget = "cloudrun"
ignorePorts = false

[[deployment.env]]
key = "FLASK_APP"
value = "main.py"

[[deployment.env]]
key = "FLASK_ENV"
value = "production"

[[deployment.env]]
key = "PYTHONUNBUFFERED"
value = "1"

[[deployment.env]]
key = "PIP_NO_CACHE_DIR"
value = "1"

[[deployment.env]]
key = "PIP_DISABLE_PIP_VERSION_CHECK"
value = "1"

[[deployment.env]]
key = "PYTHONDONTWRITEBYTECODE"
value = "1"

[deployment.build]
run = ["sh", "-c", "pip cache purge || true && pip uninstall pyee -y || true && pip install --no-cache-dir -r requirements.txt && pip install --force-reinstall --no-deps --no-cache-dir pyee==12.1.1"]

[deployment.run]
run = ["sh", "-c", "pip cache purge || true && pip uninstall pyee -y || true && pip install --force-reinstall --no-deps --no-cache-dir pyee==12.1.1 && gunicorn --bind 0.0.0.0:$PORT --workers=2 --worker-class=gthread --threads=2 --timeout=0 main:app"]

[[deployment.ports]]
localPort = 8080
externalPort = 80
