
[deployment]
deploymentTarget = "cloudrun"
ignorePorts = false

[deployment.build]
run = ["sh", "-c", "pip install --upgrade pip setuptools wheel && pip install . && pip install gunicorn>=23.0.0"]

[deployment.run]
run = ["gunicorn", "--bind", "0.0.0.0:$PORT", "--workers", "1", "--timeout", "300", "--keep-alive", "2", "--max-requests", "1000", "main:app"]

[[deployment.env]]
key = "FLASK_ENV"
value = "production"

[[deployment.env]]
key = "PYTHONUNBUFFERED"
value = "1"

[[deployment.env]]
key = "PORT"
value = "8080"
