
[deployment]
deploymentTarget = "cloudrun"
ignorePorts = false

[[deployment.env]]
key = "FLASK_APP"
value = "main.py"

[[deployment.env]]
key = "FLASK_ENV"
value = "production"

[[deployment.env]]
key = "PYTHONUNBUFFERED"
value = "1"

[deployment.build]
run = ["sh", "-c", "pip uninstall pyee -y || true && pip install --no-deps pyee==12.1.1 && pip install -r requirements.txt"]

[deployment.run]
run = ["sh", "-c", "pip uninstall pyee -y || true && pip install --no-deps pyee==12.1.1 && gunicorn --bind 0.0.0.0:$PORT --workers=2 --worker-class=gthread --threads=2 --timeout=0 main:app"]

[[deployment.ports]]
localPort = 8080
externalPort = 80
