
[deployment]
deploymentTarget = "cloudrun"
ignorePorts = false

[[deployment.env]]
key = "FLASK_APP"
value = "main.py"

[[deployment.env]]
key = "FLASK_ENV"
value = "production"

[[deployment.env]]
key = "PYTHONUNBUFFERED"
value = "1"

[[deployment.env]]
key = "PIP_NO_CACHE_DIR"
value = "1"

[[deployment.env]]
key = "PIP_DISABLE_PIP_VERSION_CHECK"
value = "1"

[[deployment.env]]
key = "PYTHONDONTWRITEBYTECODE"
value = "1"

[[deployment.env]]
key = "PIP_BREAK_SYSTEM_PACKAGES"
value = "1"

[[deployment.env]]
key = "PIP_ROOT_USER_ACTION"
value = "ignore"

[deployment.build]
run = ["sh", "-c", "export PIP_NO_CACHE_DIR=1 PIP_DISABLE_PIP_VERSION_CHECK=1 PYTHONDONTWRITEBYTECODE=1 PIP_BREAK_SYSTEM_PACKAGES=1 PIP_ROOT_USER_ACTION=ignore && echo 'Starting build with pyee corruption fixes...' && pip cache purge || true && pip uninstall pyee -y --break-system-packages || true && rm -rf ~/.cache/pip/* || true && pip install --force-reinstall --no-deps --no-cache-dir --ignore-installed pyee==12.1.1 --break-system-packages && echo 'pyee fix completed, installing requirements...' && pip install -r requirements.txt --no-cache-dir --force-reinstall --break-system-packages"]

[deployment.run]
run = ["sh", "-c", "export PIP_NO_CACHE_DIR=1 PIP_DISABLE_PIP_VERSION_CHECK=1 PYTHONDONTWRITEBYTECODE=1 PIP_BREAK_SYSTEM_PACKAGES=1 PIP_ROOT_USER_ACTION=ignore && echo 'Starting runtime with pyee corruption fixes...' && pip cache purge || true && pip uninstall pyee -y --break-system-packages || true && rm -rf ~/.cache/pip/* || true && pip install --force-reinstall --no-deps --no-cache-dir --ignore-installed pyee==12.1.1 --break-system-packages && python -c 'import pyee; print(f\"pyee verification: {pyee.__version__ if hasattr(pyee, \"__version__\") else \"imported successfully\"}\")' && echo 'Starting gunicorn server...' && exec gunicorn --bind 0.0.0.0:${PORT:-8080} --workers=2 --worker-class=gthread --threads=2 --timeout=0 --keepalive=2 --max-requests=1000 --max-requests-jitter=100 --preload --worker-connections=1000 --access-logfile=- --error-logfile=- --log-level=info --worker-tmp-dir=/dev/shm main:app"]

[[deployment.ports]]
localPort = 8080
externalPort = 80
