[deployment]
deploymentTarget = "cloudrun"
ignorePorts = false

[deployment.build]
run = ["sh", "-c", "pip install -r requirements.txt"]

[deployment.run]
run = ["sh", "-c", "gunicorn --bind 0.0.0.0:$PORT main:app --workers 2 --timeout 120"]

[[deployment.env]]
key = "FLASK_ENV"
value = "production"

[[deployment.env]]
key = "PYTHONUNBUFFERED"
value = "1"

[[deployment.env]]
key = "PORT"
value = "8080"

[[deployment.ports]]
localPort = 8080
externalPort = 80