
[deployment]
deploymentTarget = "cloudrun"
ignorePorts = false

[[deployment.env]]
key = "FLASK_APP"
value = "main.py"

[[deployment.env]]
key = "FLASK_ENV"
value = "production"

[[deployment.env]]
key = "PYTHONUNBUFFERED"
value = "1"

[[deployment.env]]
key = "PIP_NO_CACHE_DIR"
value = "1"

[[deployment.env]]
key = "PIP_DISABLE_PIP_VERSION_CHECK"
value = "1"

[[deployment.env]]
key = "PYTHONDONTWRITEBYTECODE"
value = "1"

[[deployment.env]]
key = "PIP_BREAK_SYSTEM_PACKAGES"
value = "1"

[[deployment.env]]
key = "PIP_ROOT_USER_ACTION"
value = "ignore"

[deployment.build]
run = ["pip", "install", "-r", "requirements.txt"]

[deployment.run]
run = ["gunicorn", "-c", "gunicorn.conf.py", "main:app"]

[[deployment.ports]]
localPort = 8080
externalPort = 80
