# Configuration file for Replit Deployments
run = "./run_port_8080.sh"
deploymentTarget = "cloudrun"

# Health check endpoint
healthCheckPath = "/"

# Environment configuration
[env]
# These will be overridden by Replit Secrets during deployment
ENVIRONMENT = "production"
DEBUG = "false"