[deployment]
deploymentTarget = "cloudrun"
ignorePorts = false

[[deployment.env]]
key = "FLASK_APP"
value = "main.py"

[[deployment.env]]
key = "FLASK_ENV"
value = "production"

[[deployment.env]]
key = "PYTHONUNBUFFERED"
value = "1"

[[deployment.env]]
key = "PORT"
value = "8080"

[deployment.build]
run = ["pip", "install", "--no-cache-dir", "-r", "requirements-minimal.txt"]

[deployment.run]
run = ["gunicorn", "--bind", "0.0.0.0:$PORT", "--workers=1", "--threads=2", "--timeout=30", "--max-requests=500", "--preload", "main:app"]