[nix]
channel = "stable-23_05"

[deployment]
run = ["python3", "new_port_proxy.py"]

[run]
command = ["python3", "new_port_proxy.py"]

[languages]

[languages.python3]
pattern = "**/*.py"

[languages.python3.languageServer]
start = "pylsp"